[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"


[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple"
priority = "primary"


[tool.poetry]
name = "pond"
version = "0.1.0"
description = ""
authors = ["fangyang_gpu <fangyang.jing@hotmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8"
akshare = "^1.11.63"
mootdx = "^0.11.1"
requests = "^2.31.0"
duckdb = "^0.9.2"
loguru = "^0.7.2"
black = "^23.11.0"
polars = "^0.20.4"
pyarrow = "^14.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
